#ifndef EVENTCANDIDATE_HPP
#define EVENTCANDIDATE_HPP

enum EVENT_CANDIDATE
{
    REPORT_ALL = 1,
    REPORT_RESOURCE,
    REPORT_ANIMAL,
    FEED_ANIMAL,
    LET_ANIMAL_OUT,
    BUY_ANIMAL,
    BUY_FOOD,
    SELL_ANIMAL,
    QUIT = 9
};

#endif // EVENTCANDIDATE_HPP